version: '3'
services:
  mysql:
    image: 'mysql:latest'
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379
